### ISSUE TITLE
[BUG] Swap only available from WND

### ISSUE THREAD

**Issue by Kouteki** [MVPWorkshop/dot-acp-ui#249]
**Current state**
As a user I can only swap from WND on Westmint.

**Desired state**
As a user ISBAT swap to and from WND on Westmint.

**Steps to reproduce**

1. Go to Swap
2. Connect a wallet
3. Choose **WND** in the **You receive** dropdown
4. **You buy** dropdown will be empty

![Image](https://github.com/MVPWorkshop/dot-acp-ui/assets/12710860/89bf7b90-523b-4210-a5b7-ee74bf7e4fab)

**Comment by gagi13** [comment]
This only happens when a user does not have other tokens when a native token. That is the case when he can only swap from WND but not from other tokens (since he does not have any other). For now, we leave this as it is, since there is a message showing to the user that he has no other assets in the wallet besides the native token.
