### ISSUE TITLE
Wire pricing ratio for creating liquidity pools

### ISSUE THREAD

**Issue by fjovakaric** [MVPWorkshop/dot-acp-ui#66]
Part of story #15 
After initializing the flow, the set ratio between the tokens is obligatory for everyone who is adding liquidity to that pool later. When user type in first amount the second one should be automatically calculated

**Comment by ngrujicic** [comment]
clarification: to get the pricing/amount ratio for pool we need to have a pool already created with liquidity inside, then we want to insert more tokens = add liquidity, we need to calculate the current ratio between the two tokens, so we could suggest to the user how much of each token he should add to the pool.

**Comment by ngrujicic** [comment]
things to do:
1. get the amount of each token in the pool when we click on the add liquidity(+ deposit button). (getReserves function)
2. we need to calculate the amount of the tokens in the pool in the correct format, divide the token amount with 10^decimals of that token.
3. save the result so that we can use them later for future calculations.
4. user enters the amount of one of the tokens, at that moment we use the previously saved results to calculate the pricing/amount ratio of the other token. 

how to calculate the price of the other token:
token2AmountUserPutsIN = token2AmountInPool * token1AmountUserPutsIN / token1AmountInPool
token1AmountUserPutsIN = token2AmountUserPutsIN * token1AmountInPool / token2AmountInPool
